eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761
spring:
  application:
    name: rnr-eureka-server
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
